INSERT INTO "books" VALUES (1, 1, 'Genesis', '', 'The First Book of Moses called Genesis', 'Gen.', '', 'gen', 50, 1533);
INSERT INTO "books" VALUES (2, 1, 'Exodus', '', 'The Second Book of Moses called Exodus', 'Ex.', '', 'ex', 40, 1213);
INSERT INTO "books" VALUES (3, 1, 'Leviticus', '', 'The Third Book of Moses called Leviticus', 'Lev.', '', 'lev', 27, 859);
INSERT INTO "books" VALUES (4, 1, 'Numbers', '', 'The Fourth Book of Moses called Numbers', 'Num.', '', 'num', 36, 1288);
INSERT INTO "books" VALUES (5, 1, 'Deuteronomy', '', 'The Fifth Book of Moses called Deuteronomy', 'Deut.', '', 'deut', 34, 959);
INSERT INTO "books" VALUES (6, 1, 'Joshua', '', 'The Book of Joshua', 'Josh.', '', 'josh', 24, 658);
INSERT INTO "books" VALUES (7, 1, 'Judges', '', 'The Book of Judges', 'Judg.', '', 'judg', 21, 618);
INSERT INTO "books" VALUES (8, 1, 'Ruth', '', 'The Book of Ruth', 'Ruth', '', 'ruth', 4, 85);
INSERT INTO "books" VALUES (9, 1, '1 Samuel', '', 'The First Book of Samuel', '1 Sam.', 'Otherwise called the First Book of the Kings', '1_sam', 31, 810);
INSERT INTO "books" VALUES (10, 1, '2 Samuel', '', 'The Second Book of Samuel', '2 Sam.', 'Otherwise called the Second Book of the Kings', '2_sam', 24, 695);
INSERT INTO "books" VALUES (11, 1, '1 Kings', '', 'The First Book of the Kings', '1 Kgs.', 'Commonly called the Third Book of the Kings', '1_kgs', 22, 816);
INSERT INTO "books" VALUES (12, 1, '2 Kings', '', 'The Second Book of the King', '2 Kgs.', 'Commonly called the Fourth Book of the Kings', '2_kgs', 25, 719);
INSERT INTO "books" VALUES (13, 1, '1 Chronicles', '', 'The First Book of the Chronicles', '1 Chr.', '', '1_chr', 29, 942);
INSERT INTO "books" VALUES (14, 1, '2 Chronicles', '', 'The Second Book of the Chronicles', '2 Chr.', '', '2_chr', 36, 822);
INSERT INTO "books" VALUES (15, 1, 'Ezra', '', 'Ezra', 'Ezra', '', 'ezra', 10, 280);
INSERT INTO "books" VALUES (16, 1, 'Nehemiah', '', 'The Book of Nehemiah', 'Neh.', '', 'neh', 13, 406);
INSERT INTO "books" VALUES (17, 1, 'Esther', '', 'The Book of Esther', 'Esth.', '', 'esth', 10, 167);
INSERT INTO "books" VALUES (18, 1, 'Job', '', 'The Book of Job', 'Job', '', 'job', 42, 1070);
INSERT INTO "books" VALUES (19, 1, 'Psalms', '', 'The Book of Psalms', 'Ps.', '', 'ps', 150, 2461);
INSERT INTO "books" VALUES (20, 1, 'Proverbs', '', 'The Proverbs', 'Prov.', '', 'prov', 31, 915);
INSERT INTO "books" VALUES (21, 1, 'Ecclesiastes', '', 'Ecclesiastes or, The Preacher', 'Eccl.', '', 'eccl', 12, 222);
INSERT INTO "books" VALUES (22, 1, 'Solomon''s Song', '', 'The Song of Solomon', 'Song.', '', 'song', 8, 117);
INSERT INTO "books" VALUES (23, 1, 'Isaiah', '', 'The Book of the Prophet Isaiah', 'Isa.', '', 'isa', 66, 1292);
INSERT INTO "books" VALUES (24, 1, 'Jeremiah', '', 'The Book of the Prophet Jeremiah', 'Jer.', '', 'jer', 52, 1364);
INSERT INTO "books" VALUES (25, 1, 'Lamentations', '', 'The Lamentations of Jeremiah', 'Lam.', '', 'lam', 5, 154);
INSERT INTO "books" VALUES (26, 1, 'Ezekiel', '', 'The Book of the Prophet Ezekiel', 'Ezek.', '', 'ezek', 48, 1273);
INSERT INTO "books" VALUES (27, 1, 'Daniel', '', 'The Book of Daniel', 'Dan.', '', 'dan', 12, 357);
INSERT INTO "books" VALUES (28, 1, 'Hosea', '', 'Hosea', 'Hosea', '', 'hosea', 14, 197);
INSERT INTO "books" VALUES (29, 1, 'Joel', '', 'Joel', 'Joel', '', 'joel', 3, 73);
INSERT INTO "books" VALUES (30, 1, 'Amos', '', 'Amos', 'Amos', '', 'amos', 9, 146);
INSERT INTO "books" VALUES (31, 1, 'Obadiah', '', 'Obadiah', 'Obad.', '', 'obad', 1, 21);
INSERT INTO "books" VALUES (32, 1, 'Jonah', '', 'Jonah', 'Jonah', '', 'jonah', 4, 48);
INSERT INTO "books" VALUES (33, 1, 'Micah', '', 'Micah', 'Micah', '', 'micah', 7, 105);
INSERT INTO "books" VALUES (34, 1, 'Nahum', '', 'Nahum', 'Nahum', '', 'nahum', 3, 47);
INSERT INTO "books" VALUES (35, 1, 'Habakkuk', '', 'Habakkuk', 'Hab.', '', 'hab', 3, 56);
INSERT INTO "books" VALUES (36, 1, 'Zephaniah', '', 'Zephaniah', 'Zeph.', '', 'zeph', 3, 53);
INSERT INTO "books" VALUES (37, 1, 'Haggai', '', 'Haggai', 'Hag.', '', 'hag', 2, 38);
INSERT INTO "books" VALUES (38, 1, 'Zechariah', '', 'Zechariah', 'Zech.', '', 'zech', 14, 211);
INSERT INTO "books" VALUES (39, 1, 'Malachi', '', 'Malachi', 'Mal.', '', 'mal', 4, 55);
INSERT INTO "books" VALUES (40, 2, 'Matthew', 'The Testimony of St Matthew', 'The Gospel According to St Matthew', 'Matt.', '', 'matt', 28, 1071);
INSERT INTO "books" VALUES (41, 2, 'Mark', 'The Testimony of St Mark', 'The Gospel According to St Mark', 'Mark', '', 'mark', 16, 678);
INSERT INTO "books" VALUES (42, 2, 'Luke', 'The Testimony of St Luke', 'The Gospel According to St Luke', 'Luke', '', 'luke', 24, 1151);
INSERT INTO "books" VALUES (43, 2, 'John', 'The Testimony of St John', 'The Gospel According to St John', 'John', '', 'john', 21, 879);
INSERT INTO "books" VALUES (44, 2, 'Acts', '', 'The Acts of the Apostles', 'Acts', '', 'acts', 28, 1007);
INSERT INTO "books" VALUES (45, 2, 'Romans', '', 'The Epistle of Paul the Apostle to the Romans', 'Rom.', '', 'rom', 16, 433);
INSERT INTO "books" VALUES (46, 2, '1 Corinthians', '', 'The First Epistle of Paul the Apostle to the Corinthians', '1 Cor.', '', '1_cor', 16, 437);
INSERT INTO "books" VALUES (47, 2, '2 Corinthians', '', 'The Second Epistle of Paul the Apostle to the Corinthians', '2 Cor.', '', '2_cor', 13, 257);
INSERT INTO "books" VALUES (48, 2, 'Galatians', '', 'The Epistle of Paul the Apostle to the Galatians', 'Gal.', '', 'gal', 6, 149);
INSERT INTO "books" VALUES (49, 2, 'Ephesians', '', 'The Epistle of Paul the Apostle to the Ephesians', 'Eph.', '', 'eph', 6, 155);
INSERT INTO "books" VALUES (50, 2, 'Philippians', '', 'The Epistle of Paul the Apostle to the Philippians', 'Philip.', '', 'philip', 4, 104);
INSERT INTO "books" VALUES (51, 2, 'Colossians', '', 'The Epistle of Paul the Apostle to the Colossians', 'Col.', '', 'col', 4, 95);
INSERT INTO "books" VALUES (52, 2, '1 Thessalonians', '', 'The First Epistle of Paul the Apostle to the Thessalonians', '1 Thes.', '', '1_thes', 5, 89);
INSERT INTO "books" VALUES (53, 2, '2 Thessalonians', '', 'The Second Epistle of Paul the Apostle to the Thessalonians', '2 Thes.', '', '2_thes', 3, 47);
INSERT INTO "books" VALUES (54, 2, '1 Timothy', '', 'The First Epistle of Paul the Apostle to Timothy', '1 Tim.', '', '1_tim', 6, 113);
INSERT INTO "books" VALUES (55, 2, '2 Timothy', '', 'The Second Epistle of Paul the Apostle to Timothy', '2 Tim.', '', '2_tim', 4, 83);
INSERT INTO "books" VALUES (56, 2, 'Titus', '', 'The Epistle of Paul to Titus', 'Titus', '', 'titus', 3, 46);
INSERT INTO "books" VALUES (57, 2, 'Philemon', '', 'The Epistle of Paul to Philemon', 'Philem.', '', 'philem', 1, 25);
INSERT INTO "books" VALUES (58, 2, 'Hebrews', '', 'The Epistle of Paul to the Hebrews', 'Heb.', '', 'heb', 13, 303);
INSERT INTO "books" VALUES (59, 2, 'James', '', 'The General Epistle of James', 'James', '', 'james', 5, 108);
INSERT INTO "books" VALUES (60, 2, '1 Peter', '', 'The First Epistle General of Peter', '1 Pet.', '', '1_pet', 5, 105);
INSERT INTO "books" VALUES (61, 2, '2 Peter', '', 'The Second Epistle General of Peter', '2 Pet.', '', '2_pet', 3, 61);
INSERT INTO "books" VALUES (62, 2, '1 John', '', 'The First Epistle General of John', '1 Jn.', '', '1_jn', 5, 105);
INSERT INTO "books" VALUES (63, 2, '2 John', '', 'The Second Epistle of John', '2 Jn.', '', '2_jn', 1, 13);
INSERT INTO "books" VALUES (64, 2, '3 John', '', 'The Third Epistle of John', '3 Jn.', '', '3_jn', 1, 14);
INSERT INTO "books" VALUES (65, 2, 'Jude', '', 'The General Epistle of Jude', 'Jude', '', 'jude', 1, 25);
INSERT INTO "books" VALUES (66, 2, 'Revelation', '', 'The Revelation of St John the Divine', 'Rev.', '', 'rev', 22, 404);
INSERT INTO "books" VALUES (67, 3, '1 Nephi', '', 'The First Book of Nephi', '1 Ne.', 'His Reign and Ministry', '1_ne', 22, 618);
INSERT INTO "books" VALUES (68, 3, '2 Nephi', '', 'The Second Book of Nephi', '2 Ne.', '', '2_ne', 33, 779);
INSERT INTO "books" VALUES (69, 3, 'Jacob', '', 'The Book of Jacob', 'Jacob', 'The Brother of Nephi', 'jacob', 7, 203);
INSERT INTO "books" VALUES (70, 3, 'Enos', '', 'The Book of Enos', 'Enos', '', 'enos', 1, 27);
INSERT INTO "books" VALUES (71, 3, 'Jarom', '', 'The Book of Jarom', 'Jarom', '', 'jarom', 1, 15);
INSERT INTO "books" VALUES (72, 3, 'Omni', '', 'The Book of Omni', 'Omni', '', 'omni', 1, 30);
INSERT INTO "books" VALUES (73, 3, 'Words of Mormon', '', 'Words of Mormon', 'W of M', '', 'w_of_m', 1, 18);
INSERT INTO "books" VALUES (74, 3, 'Mosiah', '', 'The Book of Mosiah', 'Mosiah', '', 'mosiah', 29, 785);
INSERT INTO "books" VALUES (75, 3, 'Alma', '', 'The Book of Alma', 'Alma', 'The Son of Alma', 'alma', 63, 1975);
INSERT INTO "books" VALUES (76, 3, 'Helaman', '', 'The Book of Helaman', 'Hel.', '', 'hel', 16, 497);
INSERT INTO "books" VALUES (77, 3, '3 Nephi', '', 'The Third Book of Nephi', '3 Ne.', 'The Book of Nephi
The Son of Nephi, who was the Son of Helaman', '3_ne', 30, 785);
INSERT INTO "books" VALUES (78, 3, '4 Nephi', '', 'The Fourth Book of Nephi', '4 Ne.', 'The Book of Nephi
Who is the son of Nephi, one of the disciples of Jesus Christ', '4_ne', 1, 49);
INSERT INTO "books" VALUES (79, 3, 'Mormon', '', 'The Book of Mormon', 'Morm.', '', 'morm', 9, 227);
INSERT INTO "books" VALUES (80, 3, 'Ether', '', 'The Book of Ether', 'Ether', '', 'ether', 15, 433);
INSERT INTO "books" VALUES (81, 3, 'Moroni', '', 'The Book of Moroni', 'Moro.', '', 'moro', 10, 163);
INSERT INTO "books" VALUES (82, 4, 'Doctrine and Covenants', '', 'The Doctrine and Covenants', 'D&C', 'of the Church of Jesus Christ of Latter-day Saints', 'dc', 138, 3654);
INSERT INTO "books" VALUES (83, 5, 'Moses', '', 'Selections from the Book of Moses', 'Moses', '', 'moses', 8, 356);
INSERT INTO "books" VALUES (84, 5, 'Abraham', '', 'The Book of Abraham', 'Abr.', 'Translated from the papyrus, by Joseph Smith', 'abr', 5, 136);
INSERT INTO "books" VALUES (85, 5, 'Joseph Smith--Matthew', '', 'Joseph Smith--Matthew', 'JS-M', '', 'js_m', 1, 55);
INSERT INTO "books" VALUES (86, 5, 'Joseph Smith--History', '', 'Joseph Smith--History', 'JS-H', 'Extracts from The History of Joseph Smith, the Prophet', 'js_h', 1, 75);
INSERT INTO "books" VALUES (87, 5, 'Articles of Faith', '', 'The Articles of Faith', 'A of F', 'Of The Church of Jesus Christ of Latter-day Saints', 'a_of_f', 1, 13);

